name: Testing

on:
  push:
    branches: [ test, main ]
  pull_request:
    branches: [ test, main ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2.1.1
        with:
          activate-environment: anaconda-client-env
          environment-file: environment.yml
          python-version: 3.8.11
          auto-activate-base: false
      - name: Test with pytest
        run: |
          conda install pytest
          pytest
